# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Nabeel Siddiqui
tagline:          'Nabeel Siddiqui'
description:      'Doctoral Candidate in American Studies at the College of William and Mary'
url:              https://nabsiddiqui.github.io
baseurl:          /nabsiddiqui.github.io/

author:
  name:           'Nabeel Siddiqui'
  url:            https://twitter.com/nabsiddiqui

paginate:         5

# Custom vars
version:          2.1.0
gems: [jekyll-paginate]

github:
  repo:           https://github.com/poole/hyde
